=head1 NAME

PPIx::Regexp::Token::Comment - Represent a comment.

=head1 SYNOPSIS

 use PPIx::Regexp::Dumper;
 PPIx::Regexp::Dumper->new( 'qr{foo(?#bar)}smx' )
     ->print();

=head1 INHERITANCE

 PPIx::Regexp::Token::Comment
 isa PPIx::Regexp::Token

=head1 DESCRIPTION

This class represents a comment - both parenthesized comments (i.e.
C<< (?# this is a comment ) >> and the /x mode end-of-line comments.

=head1 METHODS

This class provides no public methods beyond those provided by its
superclass.

=cut

package PPIx::Regexp::Token::Comment;

use strict;
use warnings;

use base qw{ PPIx::Regexp::Token };

our $VERSION = '0.000_03';

# Return true if the token can be quantified, and false otherwise
sub can_be_quantified { return };

sub significant {
    return;
}

sub comment {
    return 1;
}

# Return true to be included in the token scan. This determination
# should be good for the life of the tokenizer. It is called as a static
# method with two arguments: the tokenizer object and the mode name. Use
# of the latter is pre-deprecated.
# sub __PPIX_TOKEN__scan_me {
#     my ( $class, $tokenizer, $mode ) = @_;
#     return $tokenizer->interpolates();
# };

# This must be implemented by tokens which do not recognize themselves.
# The return is a list of list references. Each list reference must
# contain a regular expression that recognizes the token, and optionally
# a reference to a hash to pass to make_token as the class-specific
# arguments. The regular expression MUST be anchored to the beginning of
# the string.
sub __PPIX_TOKEN__recognize {
    return ( [ qr{ \A \( \? \# [^\)]* \) }smx ] );
}

# We anticipate that these tokens will be generated by other classes:
# PPIx::Regexp::Token::Structure for parenthesized comments, and
# PPIx::Regexp::Token::Literal for end-of-line /x mode comments.

=begin comment

sub __PPIX_TOKENIZER__regexp {
    my ( $class, $tokenizer, $character ) = @_;

    return $character eq 'x' ? 1 : 0;
}

=end comment

=cut

1;

__END__

=head1 SUPPORT

Support is by the author. Please file bug reports at
L<http://rt.cpan.org>, or in electronic mail to the author.

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT

Copyright 2009 by Thomas R. Wyant, III.

=cut

# ex: set textwidth=72 :
