#!/usr/local/bin/perl

use strict;
use warnings;

use Regexp::Parser;
use YAML::Any;

my $rp = Regexp::Parser->new();

$rp->parse( $ARGV[0] ) or die $rp->errmsg();

my $iter = $rp->walker();

while ( my ( $node, $depth ) = $iter->() ) {
    my $margin = '   ' x $depth;
    my $class = ref $node;
    ( my $content = $node->visual() ) =~ s/ ( [\\'] ) /\\$1/smxg;
    print "$margin$class\t'$content'\n";
}

__END__

# ex: set textwidth=72 :
